
package cn.landfun.hb110.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlowServiceService", targetNamespace = "http://ws.service.flow.neusoft.com", wsdlLocation = "http://192.168.124.32:8080/flow_ws/services/FlowService?wsdl")
public class FlowServiceService
    extends Service
{

    private final static URL FLOWSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FLOWSERVICESERVICE_EXCEPTION;
    private final static QName FLOWSERVICESERVICE_QNAME = new QName("http://ws.service.flow.neusoft.com", "FlowServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.124.32:8080/flow_ws/services/FlowService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLOWSERVICESERVICE_WSDL_LOCATION = url;
        FLOWSERVICESERVICE_EXCEPTION = e;
    }

    public FlowServiceService() {
        super(__getWsdlLocation(), FLOWSERVICESERVICE_QNAME);
    }

    public FlowServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLOWSERVICESERVICE_QNAME, features);
    }

    public FlowServiceService(URL wsdlLocation) {
        super(wsdlLocation, FLOWSERVICESERVICE_QNAME);
    }

    public FlowServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLOWSERVICESERVICE_QNAME, features);
    }

    public FlowServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlowServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlowService
     */
    @WebEndpoint(name = "FlowService")
    public FlowService getFlowService() {
        return super.getPort(new QName("http://ws.service.flow.neusoft.com", "FlowService"), FlowService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlowService
     */
    @WebEndpoint(name = "FlowService")
    public FlowService getFlowService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.flow.neusoft.com", "FlowService"), FlowService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLOWSERVICESERVICE_EXCEPTION!= null) {
            throw FLOWSERVICESERVICE_EXCEPTION;
        }
        return FLOWSERVICESERVICE_WSDL_LOCATION;
    }

}
