
package cn.landfun.hb110.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlowService", targetNamespace = "http://ws.service.flow.neusoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlowService {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "messageReturn", targetNamespace = "http://ws.service.flow.neusoft.com")
    @RequestWrapper(localName = "message", targetNamespace = "http://ws.service.flow.neusoft.com", className = "cn.landfun.hb110.client.Message")
    @ResponseWrapper(localName = "messageResponse", targetNamespace = "http://ws.service.flow.neusoft.com", className = "cn.landfun.hb110.client.MessageResponse")
    public String message(
        @WebParam(name = "xml", targetNamespace = "http://ws.service.flow.neusoft.com")
        String xml);

}
