
package cn.landfun.hb110;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonService", targetNamespace = "http://www.WebService.hb110.landfun.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonService {


    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "feedback")
    @RequestWrapper(localName = "feedback", targetNamespace = "http://www.WebService.hb110.landfun.cn", className = "cn.landfun.hb110.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://www.WebService.hb110.landfun.cn", className = "cn.landfun.hb110.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "Message", targetNamespace = "")
        String message);

}
